CREATE SCHEMA ESHOP;

CREATE TABLE ESHOP.PRODUCT (
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL ,
  DESCRIPTION VARCHAR(2000),
  PRICE DECIMAL
);

CREATE TABLE ESHOP.CLIENT (
  ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NAME VARCHAR(255) NOT NULL ,
  ADDRESS VARCHAR(1000),
  PHONE VARCHAR(15)
);

CREATE TABLE ESHOP.BASKET (
  ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CLIENT_ID INTEGER REFERENCES ESHOP.CLIENT(ID),
  TOTAL DECIMAL
);

CREATE TABLE ESHOP.ORDERED_PRODUCT (
  BASKET INTEGER REFERENCES ESHOP.BASKET(ID),
  PRODUCT INTEGER REFERENCES ESHOP.PRODUCT(ID),
  QUANTITY INTEGER NOT NULL
);