INSERT INTO ESHOP.PRODUCT VALUES (1,'Product1', 'Good product1', 100);
INSERT INTO ESHOP.PRODUCT VALUES (2,'Product2', 'Good product2', 200);
INSERT INTO ESHOP.PRODUCT VALUES (3,'Product3', 'Good product3', 300);
INSERT INTO ESHOP.PRODUCT VALUES (4,'Product4', 'Good product4', 400);
INSERT INTO ESHOP.PRODUCT VALUES (5,'Product5', 'Good product5', 500);
INSERT INTO ESHOP.PRODUCT VALUES (6,'Product6', 'Good product6', 600);
